### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by thenerdsuperuser** [redaxmedia/porn-terminal#3]
`PHP Warning:  include(src/PornTerminal/bootstrap.php): failed to open stream: No such file or directory in /home/normalguy/Desktop/porn-terminal/bin/porn-terminal on line 8
PHP Warning:  include(): Failed opening 'src/PornTerminal/bootstrap.php' for inclusion (include_path='.:/usr/share/php') in /home/normalguy/Desktop/porn-terminal/bin/porn-terminal on line 8
PHP Fatal error:  Uncaught Error: Class 'PornTerminal\Api' not found in /home/normalguy/Desktop/porn-terminal/bin/porn-terminal:12
Stack trace:
#0 {main}
  thrown in /home/normalguy/Desktop/porn-terminal/bin/porn-terminal on line 12
`

**Comment by redaxmedia** [comment]
Hello,

thanks for reporting - I think you tried to start the CLI from a path outside the project root. I refactored the code to work to relative paths - please give the latest master a try.
